language: swift
osx_image: xcode9.2
xcode_project: StellarKit.xcodeproj
xcode_scheme: StellarKit
xcode_sdk: iphonesimulator8.4

before_script:
  - brew update && brew install libsodium
  - git clone https://github.com/kinfoundation/travis-stellar-core-macos.git
  - cd travis-stellar-core-macos && ./setup.sh && cd ..
  - ./travis-stellar-core-macos/stellarcmd/stellarcmd -c ./travis-stellar-core-macos/stellarcmd/config.json info GCLBBAIDP34M4JACPQJUYNSPZCQK7IRHV7ETKV6U53JPYYUIIVDVJJFQ
  - ./travis-stellar-core-macos/stellarcmd/stellarcmd -c ./travis-stellar-core-macos/stellarcmd/config.json create GBSJ7KFU2NXACVHVN2VWQIXIV5FWH6A7OIDDTEUYTCJYGY3FJMYIDTU7
  - ./travis-stellar-core-macos/stellarcmd/stellarcmd -c ./travis-stellar-core-macos/stellarcmd/config.json info GBSJ7KFU2NXACVHVN2VWQIXIV5FWH6A7OIDDTEUYTCJYGY3FJMYIDTU7

  #Install appium
  - brew upgrade openssl
  - brew upgrade python
  - npm install -g appium
  - npm install -g wd
  - sudo pip3 install Appium-Python-Client pytest requests
  - appium &
  - git clone https://github.com/kinfoundation/Kin-Stellar-SampleApp-Automation.git
script:
  - cd KinSDK
  - xcodebuild test -scheme KinSDK -destination 'platform=iOS Simulator,name=iPhone 8 Plus'
#Build sample app
  - cd ..
  - cd KinSampleApp
  - xcodebuild -scheme KinSampleApp -destination 'platform=iOS Simulator,name=iPhone 8 Plus'
#Run automation
  - cd ..
  - cd Kin-Stellar-SampleApp-Automation
  - pytest -x -v iOS_Sanity.py
